FROM ubuntu:latest

# Evitar interacciones con el frontend al instalar paquetes
ENV DEBIAN_FRONTEND=noninteractive

# Instalar Node.js y npm
RUN curl -sL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs

# Copiar la aplicación Node.js al contenedor
COPY . /usr/src/app

# Instalar dependencias
WORKDIR /usr/src/app
RUN npm install

# Exponer el puerto en el que Node.js escuchará
EXPOSE 8080

# Iniciar el servidor Node.js
CMD ["npm", "start"]